{{- if and .Values.mlService.enabled .Values.mlService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ml-platform.fullname" . }}-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ml-platform.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ml-platform.fullname" . }}
  minReplicas: {{ .Values.mlService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.mlService.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.mlService.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.mlService.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.mlService.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.mlService.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    # Custom metrics for ML workloads
    - type: Pods
      pods:
        metric:
          name: model_inference_requests_per_second
        target:
          type: AverageValue
          averageValue: "100"
    - type: Pods
      pods:
        metric:
          name: model_prediction_latency_p95
        target:
          type: AverageValue
          averageValue: "500m"  # 500ms
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
{{- end }}