# MkDocs configuration for Customer Churn Predictor MLOps Documentation
# 
# This configuration sets up a comprehensive documentation website using MkDocs
# with Material theme for the Customer Churn Prediction MLOps platform.

site_name: Customer Churn Predictor MLOps
site_description: Comprehensive documentation for the Customer Churn Prediction MLOps platform
site_author: Terragon Labs
site_url: https://terragon-labs.github.io/customer-churn-predictor-mlops

# Repository
repo_name: terragon-labs/customer-churn-predictor-mlops
repo_url: https://github.com/terragon-labs/customer-churn-predictor-mlops
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Terragon Labs

# Configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

# Plugins
plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths: [../src]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            show_category_heading: true
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
  - awesome-pages

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.smartsymbols

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quickstart.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - CLI Usage: user-guide/cli.md
    - API Usage: user-guide/api.md
    - Data Preparation: user-guide/data-preparation.md
    - Model Training: user-guide/training.md
    - Making Predictions: user-guide/predictions.md
  - API Reference:
    - Overview: api/overview.md
    - Authentication: api/authentication.md
    - Endpoints: api/endpoints.md
    - Rate Limiting: api/rate-limiting.md
    - Error Handling: api/errors.md
  - Deployment:
    - Docker: deployment/docker.md
    - Docker Compose: deployment/docker-compose.md
    - Production Setup: deployment/production.md
    - Monitoring: deployment/monitoring.md
    - Health Checks: deployment/health-checks.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Code Style: development/code-style.md
    - Architecture: development/architecture.md
  - Operations:
    - Monitoring: operations/monitoring.md
    - Troubleshooting: operations/troubleshooting.md
    - Performance: operations/performance.md
    - Security: operations/security.md
    - Backup & Recovery: operations/backup.md
  - Code Reference:
    - Core Modules: reference/core.md
    - API Modules: reference/api.md
    - CLI Modules: reference/cli.md
    - Utilities: reference/utilities.md

# Extra
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/terragon-labs/customer-churn-predictor-mlops
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

# Additional CSS and JavaScript
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js