MODEL_PATH = "models/churn_model.joblib"
FEATURE_COLUMNS_PATH = "models/feature_columns.json"
RUN_ID_PATH = "models/mlflow_run_id.txt"
RUN_ID_ENV_VAR = "MLFLOW_RUN_ID"
MODEL_ARTIFACT_PATH = "churn_model"

# Path to save the fitted preprocessing pipeline
PREPROCESSOR_PATH = "models/preprocessor.joblib"

# Default paths to the processed datasets generated by the preprocessing step
PROCESSED_FEATURES_PATH = "data/processed/processed_features.csv"
PROCESSED_TARGET_PATH = "data/processed/processed_target.csv"

# Accuracy threshold used for monitoring. This value can be overridden
# by the `CHURN_THRESHOLD` environment variable or a CLI argument.
DEFAULT_THRESHOLD = 0.8
THRESHOLD_ENV_VAR = "CHURN_THRESHOLD"
