name: Dependency Updates

on:
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday at 6 AM
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Update Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        
        # Update requirements
        if [ -f requirements.in ]; then
          pip-compile --upgrade requirements.in
        fi
        
        if [ -f requirements-dev.in ]; then
          pip-compile --upgrade requirements-dev.in
        fi
        
    - name: Check for security vulnerabilities
      run: |
        pip install safety
        safety check --json || true
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: automated dependency updates'
        body: |
          Automated dependency updates
          
          - Updated Python dependencies
          - Security scan completed
          
          Please review the changes before merging.
        branch: dependency-updates
        delete-branch: true